baseURL: 'http://localhost/'
languageCode: 'en-us'
title: "Ben Johnson's Website"
params:
  port_name: "Ben Johsnon"
  twitter: "https://x.com/bjohnson_pro"
  facebook: "https://www.facebook.com/benjohnson77"
  instagram: "https://www.instagram.com/bjohnson.pro"
  linkedin: "https://www.linkedin.com/in/benjaminrjohnson/"
  github: "https://github.com/benjohnson77"